name: deploy-notebook

# Only run this when the master branch changes
on:
  push:
    branches:
    - master

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.10

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Store race urls
      run: python store_race_urls.py

    - name: Run the spider
      run: python scrape_race.py

    - name: Build the notebook
      run: |
        jupyter nbconvert --execute --output-dir='./html' --to html blogpost.ipynb
        # quarto render blogpost.ipynb
        
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html